---
- name: Update known hosts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure that the public ip is in SSH known_hosts
      ansible.builtin.known_hosts:
        name: "{{ bastion_host }}"
        state: present
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + bastion_host) }}"

- name: Provision OpenHPC Cluster
  hosts:
    - cluster_login
    - cluster_control
    - cluster_batch
  become: true
  roles:
    - role: stackhpc.openhpc
      openhpc_enable:
        control: "{{ inventory_hostname in groups['cluster_control'] }}"
        batch: "{{ inventory_hostname in groups['cluster_batch'] }}"
        runtime: true
      openhpc_slurm_service_enabled: true
      openhpc_slurm_control_host: "{{ groups['cluster_control'] | first }}"
      openhpc_slurm_partitions:
        - name: "compute"
      openhpc_cluster_name: openhpc
      openhpc_packages:
        - openmpi5-gnu13-ohpc
        - openblas-gnu13-ohpc
        - cmake-ohpc
    - hpc_tools

...
