#cloud-init config

disable_root: true

users:
  - name: ${username}
    groups: sudo
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh_authorized_keys:
      %{ for key in ssh_pub_keys ~}
      - ${key}
      %{ endfor ~}

mounts:
  - ["${share_export_path}", "/home", "nfs", "defaults,nfsvers=4.2"]

timezone: Europe/Rome

hostname: ${hostname}

bootcmd:
  # If you want to use a remote NFS server for the home directories on this machine, you must set the use_nfs_home_dirs boolean:
  # https://linux.die.net/man/8/nfs_selinux
  - setsebool -P use_nfs_home_dirs=true

write_files:
- path: /etc/hosts
  append: true
  content: |
    %{ for host in hosts_list ~}
    ${host.ip} ${host.name}
    %{ endfor ~}

packages:
  %{ for pkg in packages ~}
  - ${pkg}
  %{ endfor ~}

# If upgrade is true, update and upgrade packages, and reboot if required
package_update: true
package_upgrade: ${upgrade}
# Required to update the kernel
package_reboot_if_required: ${upgrade}
